/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Dorian
 */
public class JDisplay extends javax.swing.JFrame
{

    private boolean _firstMessage = true;
    private MessageObservable _messages;

    /**
     * Creates new form JDisplay
     */
    public JDisplay(MessageObservable messages)
    {
        initComponents();
        this._messages = messages;
        this.init();
    }

    private void init()
    {
        this.setResizable(false);
        this._chatText.setEditable(false);
    }

    private void appendMessageView()
    {
        String newChatText;
        if (_firstMessage)
        {
            newChatText = this._chatText.getText() + "Client : " + this._textBoxMessage.getText();
            this._firstMessage = false;
        }
        else
        {
            newChatText = this._chatText.getText() + "\n" + "Client : " + this._textBoxMessage.getText();
        }
        this._chatText.setText(newChatText);
        this._messages.setMessage(this._textBoxMessage.getText());
        this._messages.changed();
        this._messages.notifyObservers();
        this._textBoxMessage.setText("");

    }

    public void appendMessageFromController(String message)
    {
        String newChatText;
        if (_firstMessage)
        {
            newChatText = message;
            this._firstMessage = false;
        }
        else
        {
            newChatText = this._chatText.getText() + "\n" + message;
        }
        this._chatText.setText(newChatText);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        _textBoxMessage = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        jScrollPane2 = new javax.swing.JScrollPane();
        _chatText = new javax.swing.JTextPane();
        _buttonSend = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        _textBoxMessage.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                _textBoxMessageKeyPressed(evt);
            }
        });

        jScrollPane2.setViewportView(_chatText);

        _buttonSend.setText("SEND");
        _buttonSend.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                _buttonSendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(_textBoxMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(_buttonSend, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 43, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_textBoxMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_buttonSend))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Send button on click event
     *
     * @param evt
     */
    private void _buttonSendActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event__buttonSendActionPerformed
    {//GEN-HEADEREND:event__buttonSendActionPerformed
        if (!(this._textBoxMessage.getText().equals("")))
        {
            this.appendMessageView();
        }
    }//GEN-LAST:event__buttonSendActionPerformed

    /**
     * Text box on key pressed event
     *
     * @param evt
     */
    private void _textBoxMessageKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event__textBoxMessageKeyPressed
    {//GEN-HEADEREND:event__textBoxMessageKeyPressed
        if ((evt.getKeyCode() == 10) && !(this._textBoxMessage.getText().equals("")))
        {
            this.appendMessageView();
        }
    }//GEN-LAST:event__textBoxMessageKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _buttonSend;
    private javax.swing.JTextPane _chatText;
    private javax.swing.JTextField _textBoxMessage;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
